name: flutter_appsize_generator
description: This package is a simple provider for some IU components.
version: 0.1.0
repository: https://github.com/Simplifit-Solutions/flutter_appsize_generator

environment:
  sdk: ^3.0.5

dependencies:
  analyzer: ^6.0.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
